services:
  server:
    build:
      context: ./server
    container_name: college_server
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    restart: unless-stopped

  client:
    build:
      context: ./client
    container_name: college_client
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: unless-stopped